### ISSUE TITLE
Decision space Mapping

### ISSUE THREAD

**Issue by yimuchunshu** [tahmid0007/Low_Pass_ReLU#1]
Prune all the layers up to the FC2 layer and directly mimic image features with (X, Y), which is 'a' in the Matlab code. Instead of using the classify function mentioned in the paper in Algorithm 1 #, I change to the forward function by adding the 1x1x2 input layer, and I got the predicted class and score. I little bit confusing the visualization progress, and please more introduction on this , that would be very helpful. cheers mate.

**Comment by tahmid0007** [comment]
Thanks for your comment mate. only2FC, at the current state, does not directly plot the visual graphs. But all the ingredients are there for custom implementation. E.g., the classify function will give you a prob score. Based on Algo 1 in page 12 of our paper, you have to raise a flag when this score exceeds 50%. In the end, you have to connect the flagged cartesian co-ordinates in 'a'. please let me know if you require further clarification.

**Comment by yimuchunshu** [comment]
Thanks for your instant reply mate. Is it possible to upload a full demo for the visualization? I have struggled for days. You guys have done a great job.

**Comment by tahmid0007** [comment]
k = 1; count = 1;
%theta = 0:0.05:2*pi;
theta = .70:.02:2.5;
rho = 5:5:100;
for i = 1:90
    [x(i),y(i)] = pol2cart(theta(1,i),rho(1,2))
    
    a(1,1,1) = x(i);
    a(1,1,2) = y(i);
    
    [labels scores] = classify(only2fc, a);
    if scores(2) < .5
        xx(1) = x(i);
        yy(1) = y(i);
        break;
    end
end
for j = i:90
    [x(j),y(j)] = pol2cart(theta(1,j),rho(1,2))
    
    a(1,1,1) = x(j);
    a(1,1,2) = y(j);
    
    [labels scores] = classify(only2fc, a);
    if scores(7) < .5
        xx(2) = x(j);
        yy(2) = y(j);
        break;
    end
end

for j1 = j:90
    [x(j1),y(j1)] = pol2cart(theta(1,j1),rho(1,2))
    
    a(1,1,1) = x(j1);
    a(1,1,2) = y(j1);
    
    [labels scores] = classify(only2fc, a);
    if scores(5) < .5
        xx(3) = x(j1);
        yy(3) = y(j1);
        break;
    end
end
scatter(xx,yy,140,'filled');

I believe this will get you started. This code block will generate 3 sample points. You have to run the loop with extended rho and theta values to accumulate all the points. To reproduce images like that of our paper, you have to plot your own 2d features first. This is why the code is left for custom implementation. I believe you get it now :). Thanks for your interest mate.

**Comment by yimuchunshu** [comment]
Sorry for the late reply. Love from China. Maybe I have a problem with the pruned FC2Net.  I just let it alone now and write my dissertation first. It is my pleasure to have the Low-pass relu on my paper and will cite it properly. Lol. Good wishes are for everyone who is effected by the bushfire in Australia.

**Comment by tahmid0007** [comment]
Thanks for your kind words and best wishes for your dissertation.
